name: im2024
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.12
  - pandas=2.2.3=py312h5da7b33_0
  - pandas-stubs=2.3.0.250703=pyhd8ed1ab_0
  - numpy=1.26.4=py312hfd52020_0
  - numpy-base=1.26.4=py312h4dde369_0
  - scikit-learn=1.6.1=py312h816cc57_0
  - scipy=1.14.1=py312h9d85e7c_0
  - pytorch=2.5.1=py3.12_cpu_0
  - pytorch-mutex=1.0=cpu
  - transformers=5.0.0=pyhd8ed1ab_0
  - datasets=2.19.1=py312haa95532_0
  - spacy=3.8.11=py312he3e9d37_0
  - spacy-legacy=3.0.12=pyhd8ed1ab_0
  - spacy-loggers=1.0.5=pyhd8ed1ab_0
  - nltk=3.9.1=py312haa95532_0
  - regex=2024.9.11=py312h827c3e9_0
  - matplotlib=3.10.8=py312h2e8e312_0
  - matplotlib-base=3.10.8=py312h26e45b9_0
  - matplotlib-inline=0.1.6=py312haa95532_0
  - matplotlib-venn=1.1.1=pyhd8ed1ab_1
  - seaborn=0.13.2=py312haa95532_3
  - tqdm=4.66.5=py312hfc267ef_0
  - joblib=1.4.2=py312haa95532_0
  - optuna=4.7.0=pyhd8ed1ab_0
  - jupyterlab=4.4.3=pyhd8ed1ab_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.27.3=py312haa95532_0
  - jupyterlab_widgets=3.0.15=pyhd8ed1ab_0
  - ipykernel=6.31.0=py312h4442805_0
  - pip=24.2=py312haa95532_0
  - pip:
      - accelerate
      - wandb
      - krippendorff
